// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package repository

import (
	"context"
)

const findAllActiveChannel = `-- name: FindAllActiveChannel :many
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_title, active, playlist_id FROM CHANNEL
WHERE ACTIVE = 1
`

func (q *Queries) FindAllActiveChannel(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, findAllActiveChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupTitle,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllChannel = `-- name: FindAllChannel :many
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_title, active, playlist_id FROM CHANNEL
`

func (q *Queries) FindAllChannel(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, findAllChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupTitle,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllChannelPagination = `-- name: FindAllChannelPagination :many
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_title, active, playlist_id FROM CHANNEL
ORDER BY PLAYLIST_ID, ID
LIMIT ?2
OFFSET ?1
`

type FindAllChannelPaginationParams struct {
	Page     int64 `json:"page"`
	Pagesize int64 `json:"pagesize"`
}

func (q *Queries) FindAllChannelPagination(ctx context.Context, arg FindAllChannelPaginationParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, findAllChannelPagination, arg.Page, arg.Pagesize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupTitle,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findChannelById = `-- name: FindChannelById :one
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_title, active, playlist_id FROM CHANNEL
WHERE ID = ? LIMIT 1
`

func (q *Queries) FindChannelById(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, findChannelById, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Length,
		&i.Uri,
		&i.TvgID,
		&i.TvgName,
		&i.TvgLogo,
		&i.GroupTitle,
		&i.Active,
		&i.PlaylistID,
	)
	return i, err
}

const saveChannel = `-- name: SaveChannel :one
INSERT INTO CHANNEL
    (NAME, LENGTH, URI, TVG_ID, TVG_NAME, TVG_LOGO, GROUP_TITLE, PLAYLIST_ID)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_title, active, playlist_id
`

type SaveChannelParams struct {
	Name       string  `json:"name"`
	Length     *int64  `json:"length"`
	Uri        string  `json:"uri"`
	TvgID      *string `json:"tvg_id"`
	TvgName    *string `json:"tvg_name"`
	TvgLogo    *string `json:"tvg_logo"`
	GroupTitle *string `json:"group_title"`
	PlaylistID *int64  `json:"playlist_id"`
}

func (q *Queries) SaveChannel(ctx context.Context, arg SaveChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, saveChannel,
		arg.Name,
		arg.Length,
		arg.Uri,
		arg.TvgID,
		arg.TvgName,
		arg.TvgLogo,
		arg.GroupTitle,
		arg.PlaylistID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Length,
		&i.Uri,
		&i.TvgID,
		&i.TvgName,
		&i.TvgLogo,
		&i.GroupTitle,
		&i.Active,
		&i.PlaylistID,
	)
	return i, err
}
