// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package repository

import (
	"context"
	"strings"
)

const findAllActiveChannel = `-- name: FindAllActiveChannel :many
SELECT channel.id, channel.name, channel.length, channel.uri, channel.tvg_id, channel.tvg_name, channel.tvg_logo, channel.group_id, channel.active, channel.playlist_id, cgroup.id, cgroup.title, cgroup.active, cgroup.playlist_id FROM CHANNEL
INNER JOIN CGROUP ON CHANNEL.GROUP_ID = CGROUP.ID
WHERE CHANNEL.ACTIVE = 1
`

type FindAllActiveChannelRow struct {
	Channel Channel `json:"channel"`
	Cgroup  Cgroup  `json:"cgroup"`
}

func (q *Queries) FindAllActiveChannel(ctx context.Context) ([]FindAllActiveChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllActiveChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllActiveChannelRow
	for rows.Next() {
		var i FindAllActiveChannelRow
		if err := rows.Scan(
			&i.Channel.ID,
			&i.Channel.Name,
			&i.Channel.Length,
			&i.Channel.Uri,
			&i.Channel.TvgID,
			&i.Channel.TvgName,
			&i.Channel.TvgLogo,
			&i.Channel.GroupID,
			&i.Channel.Active,
			&i.Channel.PlaylistID,
			&i.Cgroup.ID,
			&i.Cgroup.Title,
			&i.Cgroup.Active,
			&i.Cgroup.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllChannel = `-- name: FindAllChannel :many
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_id, active, playlist_id FROM CHANNEL
`

func (q *Queries) FindAllChannel(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, findAllChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupID,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllChannelAndGroup = `-- name: FindAllChannelAndGroup :many
SELECT channel.id, channel.name, channel.length, channel.uri, channel.tvg_id, channel.tvg_name, channel.tvg_logo, channel.group_id, channel.active, channel.playlist_id, cgroup.id, cgroup.title, cgroup.active, cgroup.playlist_id FROM CHANNEL
INNER JOIN CGROUP ON CHANNEL.GROUP_ID = CGROUP.ID
ORDER BY CHANNEL.PLAYLIST_ID, CHANNEL.ID
`

type FindAllChannelAndGroupRow struct {
	Channel Channel `json:"channel"`
	Cgroup  Cgroup  `json:"cgroup"`
}

func (q *Queries) FindAllChannelAndGroup(ctx context.Context) ([]FindAllChannelAndGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllChannelAndGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllChannelAndGroupRow
	for rows.Next() {
		var i FindAllChannelAndGroupRow
		if err := rows.Scan(
			&i.Channel.ID,
			&i.Channel.Name,
			&i.Channel.Length,
			&i.Channel.Uri,
			&i.Channel.TvgID,
			&i.Channel.TvgName,
			&i.Channel.TvgLogo,
			&i.Channel.GroupID,
			&i.Channel.Active,
			&i.Channel.PlaylistID,
			&i.Cgroup.ID,
			&i.Cgroup.Title,
			&i.Cgroup.Active,
			&i.Cgroup.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findChannelById = `-- name: FindChannelById :one
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_id, active, playlist_id FROM CHANNEL
WHERE ID = ? LIMIT 1
`

func (q *Queries) FindChannelById(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, findChannelById, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Length,
		&i.Uri,
		&i.TvgID,
		&i.TvgName,
		&i.TvgLogo,
		&i.GroupID,
		&i.Active,
		&i.PlaylistID,
	)
	return i, err
}

const findChannelByPlaylist = `-- name: FindChannelByPlaylist :many
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_id, active, playlist_id FROM CHANNEL
WHERE PLAYLIST_ID = ?
`

func (q *Queries) FindChannelByPlaylist(ctx context.Context, playlistID *int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, findChannelByPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupID,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findChannelByPlaylistAndGroup = `-- name: FindChannelByPlaylistAndGroup :many
SELECT id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_id, active, playlist_id FROM CHANNEL
WHERE PLAYLIST_ID = ?
AND GROUP_ID = ?
`

type FindChannelByPlaylistAndGroupParams struct {
	PlaylistID *int64 `json:"playlist_id"`
	GroupID    *int64 `json:"group_id"`
}

func (q *Queries) FindChannelByPlaylistAndGroup(ctx context.Context, arg FindChannelByPlaylistAndGroupParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, findChannelByPlaylistAndGroup, arg.PlaylistID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupID,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveChannel = `-- name: SaveChannel :one
INSERT INTO CHANNEL
    (NAME, LENGTH, URI, TVG_ID, TVG_NAME, TVG_LOGO, GROUP_ID, PLAYLIST_ID)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_id, active, playlist_id
`

type SaveChannelParams struct {
	Name       string  `json:"name"`
	Length     *int64  `json:"length"`
	Uri        string  `json:"uri"`
	TvgID      *string `json:"tvg_id"`
	TvgName    *string `json:"tvg_name"`
	TvgLogo    *string `json:"tvg_logo"`
	GroupID    *int64  `json:"group_id"`
	PlaylistID *int64  `json:"playlist_id"`
}

func (q *Queries) SaveChannel(ctx context.Context, arg SaveChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, saveChannel,
		arg.Name,
		arg.Length,
		arg.Uri,
		arg.TvgID,
		arg.TvgName,
		arg.TvgLogo,
		arg.GroupID,
		arg.PlaylistID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Length,
		&i.Uri,
		&i.TvgID,
		&i.TvgName,
		&i.TvgLogo,
		&i.GroupID,
		&i.Active,
		&i.PlaylistID,
	)
	return i, err
}

const updateChannelsDisable = `-- name: UpdateChannelsDisable :many
UPDATE CHANNEL
SET ACTIVE = 0
WHERE ID IN (/*SLICE:ids*/?)
RETURNING id, name, length, uri, tvg_id, tvg_name, tvg_logo, group_id, active, playlist_id
`

func (q *Queries) UpdateChannelsDisable(ctx context.Context, ids []int64) ([]Channel, error) {
	query := updateChannelsDisable
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Length,
			&i.Uri,
			&i.TvgID,
			&i.TvgName,
			&i.TvgLogo,
			&i.GroupID,
			&i.Active,
			&i.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
