// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filter.sql

package repository

import (
	"context"
)

const findAllFilter = `-- name: FindAllFilter :many
SELECT "filter".id, "filter".name, "filter".playlist_id, "filter".group_id, "filter".include, "filter"."exclude", "filter".active, playlist.id, playlist.name, playlist.uri, playlist.active, cgroup.id, cgroup.title, cgroup.active, cgroup.playlist_id
FROM FILTER
INNER JOIN CGROUP on CGROUP.ID = FILTER.GROUP_ID
INNER JOIN PLAYLIST on PLAYLIST.ID = FILTER.PLAYLIST_ID
`

type FindAllFilterRow struct {
	Filter   Filter   `json:"filter"`
	Playlist Playlist `json:"playlist"`
	Cgroup   Cgroup   `json:"cgroup"`
}

func (q *Queries) FindAllFilter(ctx context.Context) ([]FindAllFilterRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllFilterRow
	for rows.Next() {
		var i FindAllFilterRow
		if err := rows.Scan(
			&i.Filter.ID,
			&i.Filter.Name,
			&i.Filter.PlaylistID,
			&i.Filter.GroupID,
			&i.Filter.Include,
			&i.Filter.Exclude,
			&i.Filter.Active,
			&i.Playlist.ID,
			&i.Playlist.Name,
			&i.Playlist.Uri,
			&i.Playlist.Active,
			&i.Cgroup.ID,
			&i.Cgroup.Title,
			&i.Cgroup.Active,
			&i.Cgroup.PlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFilter = `-- name: SaveFilter :one
INSERT INTO FILTER
    (NAME, PLAYLIST_ID, GROUP_ID, INCLUDE, EXCLUDE)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, playlist_id, group_id, include, "exclude", active
`

type SaveFilterParams struct {
	Name       string  `json:"name"`
	PlaylistID *int64  `json:"playlist_id"`
	GroupID    *int64  `json:"group_id"`
	Include    *string `json:"include"`
	Exclude    *string `json:"exclude"`
}

func (q *Queries) SaveFilter(ctx context.Context, arg SaveFilterParams) (Filter, error) {
	row := q.db.QueryRowContext(ctx, saveFilter,
		arg.Name,
		arg.PlaylistID,
		arg.GroupID,
		arg.Include,
		arg.Exclude,
	)
	var i Filter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaylistID,
		&i.GroupID,
		&i.Include,
		&i.Exclude,
		&i.Active,
	)
	return i, err
}
