// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package repository

import (
	"context"
)

const findAllGroup = `-- name: FindAllGroup :many
SELECT cgroup.id, cgroup.title, cgroup.active, cgroup.playlist_id, playlist.id, playlist.name, playlist.uri, playlist.active FROM CGROUP
INNER JOIN PLAYLIST ON PLAYLIST.ID=CGROUP.PLAYLIST_ID
`

type FindAllGroupRow struct {
	Cgroup   Cgroup   `json:"cgroup"`
	Playlist Playlist `json:"playlist"`
}

func (q *Queries) FindAllGroup(ctx context.Context) ([]FindAllGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllGroupRow
	for rows.Next() {
		var i FindAllGroupRow
		if err := rows.Scan(
			&i.Cgroup.ID,
			&i.Cgroup.Title,
			&i.Cgroup.Active,
			&i.Cgroup.PlaylistID,
			&i.Playlist.ID,
			&i.Playlist.Name,
			&i.Playlist.Uri,
			&i.Playlist.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveGroup = `-- name: SaveGroup :one
INSERT INTO CGROUP
    (TITLE, PLAYLIST_ID)
VALUES (?, ?)
RETURNING id, title, active, playlist_id
`

type SaveGroupParams struct {
	Title      string `json:"title"`
	PlaylistID *int64 `json:"playlist_id"`
}

func (q *Queries) SaveGroup(ctx context.Context, arg SaveGroupParams) (Cgroup, error) {
	row := q.db.QueryRowContext(ctx, saveGroup, arg.Title, arg.PlaylistID)
	var i Cgroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Active,
		&i.PlaylistID,
	)
	return i, err
}
