// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

type Channel struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	Length     *int64  `json:"length"`
	Uri        string  `json:"uri"`
	TvgID      *string `json:"tvg_id"`
	TvgName    *string `json:"tvg_name"`
	TvgLogo    *string `json:"tvg_logo"`
	GroupTitle *string `json:"group_title"`
	Active     int64   `json:"active"`
	PlaylistID *int64  `json:"playlist_id"`
}

type Playlist struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Uri    string `json:"uri"`
	Active bool   `json:"active"`
}
