// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

type Cgroup struct {
	ID         int64  `json:"id"`
	Title      string `json:"title"`
	Active     bool   `json:"active"`
	PlaylistID *int64 `json:"playlist_id"`
}

type Channel struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	Length     *int64  `json:"length"`
	Uri        string  `json:"uri"`
	TvgID      *string `json:"tvg_id"`
	TvgName    *string `json:"tvg_name"`
	TvgLogo    *string `json:"tvg_logo"`
	GroupID    *int64  `json:"group_id"`
	Active     bool    `json:"active"`
	PlaylistID *int64  `json:"playlist_id"`
}

type Filter struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	PlaylistID *int64  `json:"playlist_id"`
	GroupID    *int64  `json:"group_id"`
	Include    *string `json:"include"`
	Exclude    *string `json:"exclude"`
	Active     bool    `json:"active"`
}

type Playlist struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Uri    string `json:"uri"`
	Active bool   `json:"active"`
}
