// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package repository

import (
	"context"
)

const findAllPlaylist = `-- name: FindAllPlaylist :many
SELECT id, name, uri, active FROM PLAYLIST
`

func (q *Queries) FindAllPlaylist(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, findAllPlaylist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Uri,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlaylistById = `-- name: FindPlaylistById :one
SELECT id, name, uri, active FROM PLAYLIST
WHERE ID = ? LIMIT 1
`

func (q *Queries) FindPlaylistById(ctx context.Context, id int64) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, findPlaylistById, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uri,
		&i.Active,
	)
	return i, err
}

const findPlaylistByUri = `-- name: FindPlaylistByUri :one
SELECT id, name, uri, active FROM PLAYLIST
WHERE URI = ? LIMIT 1
`

func (q *Queries) FindPlaylistByUri(ctx context.Context, uri string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, findPlaylistByUri, uri)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uri,
		&i.Active,
	)
	return i, err
}

const savePlaylist = `-- name: SavePlaylist :one
INSERT INTO PLAYLIST (NAME, URI)
VALUES (?, ?)
RETURNING id, name, uri, active
`

type SavePlaylistParams struct {
	Name string `json:"name"`
	Uri  string `json:"uri"`
}

func (q *Queries) SavePlaylist(ctx context.Context, arg SavePlaylistParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, savePlaylist, arg.Name, arg.Uri)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uri,
		&i.Active,
	)
	return i, err
}
