-- +goose Up
PRAGMA foreign_keys=ON;

CREATE TABLE PLAYLIST (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    URI TEXT NOT NULL UNIQUE,
    ACTIVE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE CHANNEL (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    LENGTH INTEGER,
    URI TEXT NOT NULL,
    TVG_ID TEXT,
    TVG_NAME TEXT,
    TVG_LOGO TEXT,
    GROUP_TITLE TEXT,
    ACTIVE INTEGER NOT NULL DEFAULT 1,
    PLAYLIST_ID INTEGER,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- +goose Down
PRAGMA foreign_keys=OFF;

DROP TABLE TRACK;
DROP TABLE PLAYLIST;
