-- +goose Up
PRAGMA foreign_keys=ON;

CREATE TABLE PLAYLIST (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    URI TEXT NOT NULL UNIQUE,
    ACTIVE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE CGROUP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    ACTIVE INTEGER NOT NULL DEFAULT 1,
    PLAYLIST_ID INTEGER,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE CHANNEL (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    LENGTH INTEGER,
    URI TEXT NOT NULL,
    TVG_ID TEXT,
    TVG_NAME TEXT,
    TVG_LOGO TEXT,
    GROUP_ID INTEGER,
    ACTIVE INTEGER NOT NULL DEFAULT 1,
    PLAYLIST_ID INTEGER,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES CGROUP(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

INSERT INTO SQLITE_SEQUENCE
    (name, seq)
VALUES('CHANNEL', 999);

CREATE TABLE FILTER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PLAYLIST_ID INTEGER,
    GROUP_ID INTEGER,
    INCLUDE TEXT,
    EXCLUDE TEXT,
    ACTIVE INTEGER DEFAULT 1,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES CGROUP(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- +goose Down
PRAGMA foreign_keys=OFF;

DROP TABLE PLAYLIST;
DROP TABLE CGROUP;
DROP TABLE CHANNEL;
DELETE FROM SQLITE_SEQUENCE
WHERE NAME = 'CHANNEL';
DROP TABLE FILTER;
