-- name: FindAllFilter :many
SELECT sqlc.embed(FILTER), sqlc.embed(PLAYLIST), sqlc.embed(CGROUP)
FROM FILTER
INNER JOIN CGROUP on CGROUP.ID = FILTER.GROUP_ID
INNER JOIN PLAYLIST on PLAYLIST.ID = FILTER.PLAYLIST_ID;

-- name: SaveFilter :one
INSERT INTO FILTER
    (NAME, PLAYLIST_ID, GROUP_ID, INCLUDE, EXCLUDE)
VALUES (?, ?, ?, ?, ?)
RETURNING *;
